### ISSUE TITLE
Bump to latest coffi version

### ISSUE THREAD

**Issue by agorgl** [IGJoshua/glfw-clj#2]
Could you please update the `coffi` dependency to match the latest coffi version?
Currently, when trying to use `glfw-clj` with other ffi-wrappers that depend on latest coffi version, it breaks because of the different jvm flags needed and panama packages used (glfw-clj's coffi version seems to be in the pre-jdk 19 coffi transition)

Thanks for the amazing wrapper!

**Comment by IGJoshua** [comment]
I will absolutely update! At the moment I'm waiting to update this until I finish the JDK 21 version of coffi.

**Comment by agorgl** [comment]
Thank you!
Targeting latest LTS JDK will be a step in a good direction too!

**Comment by IGJoshua** [comment]
Version 1.0.86 has now been released depending on coffi v1.0.450 and JDK 22+
